bot:
  server:
    id: 1457054525205643331
  activity:
    status: "online"
    name: "Text under nickname in member list"
    type: "playing"
  roles:
    roles:
    autorole:
      id: 0
      name: "Auto-role"
    verified:
      id: 0
      name: "Verified"
    owner:
      id: 0
      name: "Owner"
    admin:
      id: 0
      name: "Admin"
    trusted:
      id: 0
      name: "Trusted"
    moderator:
      id: 0
      name: "Moderator"
    partner:
      id: 0
      name: "Partner"
  channels:
    stats_membercount:
      id: 0
      name: "Member count channel"
      template: "ᴀʟʟ ᴍᴇᴍʙᴇʀs: {count}"
