bot:
  server:
    id: 1457054525205643331
  activity:
    status: "idle"
    name: "üöß DEV MODE"
    type: "playing"
  roles:
    autorole:
      id: 1457098745970950145
      name: "Auto-role"
    verified:
      id: 1457098813365026939
      name: "Verified"
    owner:
      id: 1457083591266926696
      name: "Owner"
    dep_owner:
      id: 1458866457948459199
      name: "Dep Owner"
    admin:
      id: 1457135636472402182
      name: "Admin"
    trusted:
      id: 1457127953535209472
      name: "Trusted"
    moderator:
      id: 1457127472775565625
      name: "Moderator"
    partner:
      id: 1457395670368653569
      name: "Partner"
  channels:
    stats_membercount:
      id: 1457098492387393556
      name: "Member count channel"
      template: "·¥Ä ü ü ·¥ç·¥á·¥ç ô·¥á Äs: {count}"
  categories:
    mod_tickets:
      id: 1458944075645452329
    archive_mod_tickets:
      id: 1459395263612584018
  modals:
    mod_ticket:
      title: "MOD_TICKET_TITLE"
      timeout: 600
      custom_id: "mod_ticket"
      questions:
        - label: "–°–∫–æ–ª—å–∫–æ –≤—ã –ø—Ä–æ–≤–æ–¥–∏—Ç–µ –≤—Ä–µ–º–µ–Ω–∏ –∑–∞ –∫–æ–º–ø—å—é—Ç–µ—Ä–æ–º?"
          style: "short"
          placeholder: "1—á-24—á"
          custom_id: "pc_time"

        - label: "–ö–∞–∫–æ–π —É –≤–∞—Å —á–∞—Å–æ–≤–æ–π –ø–æ—è—Å –æ—Ç –ú–°–ö?"
          style: "short"
          placeholder: "-2 –º—Å–∫"
          custom_id: "timezone"

        - label: "–ü–æ—á–µ–º—É –º—ã –º–æ–∂–µ–º –¥–æ–≤–µ—Ä–∏—Ç—Å—è –∏–º–µ–Ω–Ω–æ –≤–∞–º?"
          style: "long"
          placeholder: ""
          custom_id: "trust_reason"